//using System.Collections;
//using System.Collections.Generic;
//using UnityEngine;
//using Normal.Realtime.Serialization;
//using Normal.Realtime;

//namespace Assets.Scripts
//{
//    [RealtimeModel]
//    public partial class SlidingScaleSyncModel
//    {   
//        // 1, 11
//        [RealtimeProperty(1, true, true)] private float _scaleValue;
//    }
//}

/* ----- Begin Normal Autogenerated Code ----- */
//namespace Assets.Scripts {
//    public partial class SlidingScaleSyncModel : RealtimeModel {
//        public float scaleValue {
//            get {
//                return _cache.LookForValueInCache(_scaleValue, entry => entry.scaleValueSet, entry => entry.scaleValue);
//            }
//            set {
//                if (this.scaleValue == value) return;
//                _cache.UpdateLocalCache(entry => { entry.scaleValueSet = true; entry.scaleValue = value; return entry; });
//                InvalidateReliableLength();
//                FireScaleValueDidChange(value);
//            }
//        }
        
//        public delegate void PropertyChangedHandler<in T>(SlidingScaleSyncModel model, T value);
//        public event PropertyChangedHandler<float> scaleValueDidChange;
        
//        private struct LocalCacheEntry {
//            public bool scaleValueSet;
//            public float scaleValue;
//        }
        
//        private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
        
//        public enum PropertyID : uint {
//            ScaleValue = 11,
//        }
        
//        public SlidingScaleSyncModel() : this(null) {
//        }
        
//        public SlidingScaleSyncModel(RealtimeModel parent) : base(null, parent) {
//        }
        
//        protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
//            UnsubscribeClearCacheCallback();
//        }
        
//        private void FireScaleValueDidChange(float value) {
//            try {
//                scaleValueDidChange?.Invoke(this, value);
//            } catch (System.Exception exception) {
//                UnityEngine.Debug.LogException(exception);
//            }
//        }
        
//        protected override int WriteLength(StreamContext context) {
//            int length = 0;
//            if (context.fullModel) {
//                FlattenCache();
//                length += WriteStream.WriteFloatLength((uint)PropertyID.ScaleValue);
//            } else if (context.reliableChannel) {
//                LocalCacheEntry entry = _cache.localCache;
//                if (entry.scaleValueSet) {
//                    length += WriteStream.WriteFloatLength((uint)PropertyID.ScaleValue);
//                }
//            }
//            return length;
//        }
        
//        protected override void Write(WriteStream stream, StreamContext context) {
//            var didWriteProperties = false;
            
//            if (context.fullModel) {
//                stream.WriteFloat((uint)PropertyID.ScaleValue, _scaleValue);
//            } else if (context.reliableChannel) {
//                LocalCacheEntry entry = _cache.localCache;
//                if (entry.scaleValueSet) {
//                    _cache.PushLocalCacheToInflight(context.updateID);
//                    ClearCacheOnStreamCallback(context);
//                }
//                if (entry.scaleValueSet) {
//                    stream.WriteFloat((uint)PropertyID.ScaleValue, entry.scaleValue);
//                    didWriteProperties = true;
//                }
                
//                if (didWriteProperties) InvalidateReliableLength();
//            }
//        }
        
//        protected override void Read(ReadStream stream, StreamContext context) {
//            while (stream.ReadNextPropertyID(out uint propertyID)) {
//                switch (propertyID) {
//                    case (uint)PropertyID.ScaleValue: {
//                        float previousValue = _scaleValue;
//                        _scaleValue = stream.ReadFloat();
//                        bool scaleValueExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.scaleValueSet);
//                        if (!scaleValueExistsInChangeCache && _scaleValue != previousValue) {
//                            FireScaleValueDidChange(_scaleValue);
//                        }
//                        break;
//                    }
//                    default: {
//                        stream.SkipProperty();
//                        break;
//                    }
//                }
//            }
//        }
        
//        #region Cache Operations
        
//        private StreamEventDispatcher _streamEventDispatcher;
        
//        private void FlattenCache() {
//            _scaleValue = scaleValue;
//            _cache.Clear();
//        }
        
//        private void ClearCache(uint updateID) {
//            _cache.RemoveUpdateFromInflight(updateID);
//        }
        
//        private void ClearCacheOnStreamCallback(StreamContext context) {
//            if (_streamEventDispatcher != context.dispatcher) {
//                UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
//            }
//            _streamEventDispatcher = context.dispatcher;
//            _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
//        }
        
//        private void UnsubscribeClearCacheCallback() {
//            if (_streamEventDispatcher != null) {
//                _streamEventDispatcher.RemoveStreamCallback(ClearCache);
//                _streamEventDispatcher = null;
//            }
//        }
        
//        #endregion
//    }
//}
/* ----- End Normal Autogenerated Code ----- */
