using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

namespace Assets.Scripts
{
    [RealtimeModel]
    public partial class TeleportToSceneModel
    {
        [RealtimeProperty(1, true, true)] private int _sceneId;
        [RealtimeProperty(2, true, true)] private int _secondsDelay;
    }
}

/* ----- Begin Normal Autogenerated Code ----- */
namespace Assets.Scripts {
    public partial class TeleportToSceneModel : RealtimeModel {
        public int sceneId {
            get {
                return _cache.LookForValueInCache(_sceneId, entry => entry.sceneIdSet, entry => entry.sceneId);
            }
            set {
                if (this.sceneId == value) return;
                _cache.UpdateLocalCache(entry => { entry.sceneIdSet = true; entry.sceneId = value; return entry; });
                InvalidateReliableLength();
                FireSceneIdDidChange(value);
            }
        }
        
        public int secondsDelay {
            get {
                return _cache.LookForValueInCache(_secondsDelay, entry => entry.secondsDelaySet, entry => entry.secondsDelay);
            }
            set {
                if (this.secondsDelay == value) return;
                _cache.UpdateLocalCache(entry => { entry.secondsDelaySet = true; entry.secondsDelay = value; return entry; });
                InvalidateReliableLength();
                FireSecondsDelayDidChange(value);
            }
        }
        
        public delegate void PropertyChangedHandler<in T>(TeleportToSceneModel model, T value);
        public event PropertyChangedHandler<int> sceneIdDidChange;
        public event PropertyChangedHandler<int> secondsDelayDidChange;
        
        private struct LocalCacheEntry {
            public bool sceneIdSet;
            public int sceneId;
            public bool secondsDelaySet;
            public int secondsDelay;
        }
        
        private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
        
        public enum PropertyID : uint {
            SceneId = 1,
            SecondsDelay = 2,
        }
        
        public TeleportToSceneModel() : this(null) {
        }
        
        public TeleportToSceneModel(RealtimeModel parent) : base(null, parent) {
        }
        
        protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
            UnsubscribeClearCacheCallback();
        }
        
        private void FireSceneIdDidChange(int value) {
            try {
                sceneIdDidChange?.Invoke(this, value);
            } catch (System.Exception exception) {
                UnityEngine.Debug.LogException(exception);
            }
        }
        
        private void FireSecondsDelayDidChange(int value) {
            try {
                secondsDelayDidChange?.Invoke(this, value);
            } catch (System.Exception exception) {
                UnityEngine.Debug.LogException(exception);
            }
        }
        
        protected override int WriteLength(StreamContext context) {
            int length = 0;
            if (context.fullModel) {
                FlattenCache();
                length += WriteStream.WriteVarint32Length((uint)PropertyID.SceneId, (uint)_sceneId);
                length += WriteStream.WriteVarint32Length((uint)PropertyID.SecondsDelay, (uint)_secondsDelay);
            } else if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.sceneIdSet) {
                    length += WriteStream.WriteVarint32Length((uint)PropertyID.SceneId, (uint)entry.sceneId);
                }
                if (entry.secondsDelaySet) {
                    length += WriteStream.WriteVarint32Length((uint)PropertyID.SecondsDelay, (uint)entry.secondsDelay);
                }
            }
            return length;
        }
        
        protected override void Write(WriteStream stream, StreamContext context) {
            var didWriteProperties = false;
            
            if (context.fullModel) {
                stream.WriteVarint32((uint)PropertyID.SceneId, (uint)_sceneId);
                stream.WriteVarint32((uint)PropertyID.SecondsDelay, (uint)_secondsDelay);
            } else if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.sceneIdSet || entry.secondsDelaySet) {
                    _cache.PushLocalCacheToInflight(context.updateID);
                    ClearCacheOnStreamCallback(context);
                }
                if (entry.sceneIdSet) {
                    stream.WriteVarint32((uint)PropertyID.SceneId, (uint)entry.sceneId);
                    didWriteProperties = true;
                }
                if (entry.secondsDelaySet) {
                    stream.WriteVarint32((uint)PropertyID.SecondsDelay, (uint)entry.secondsDelay);
                    didWriteProperties = true;
                }
                
                if (didWriteProperties) InvalidateReliableLength();
            }
        }
        
        protected override void Read(ReadStream stream, StreamContext context) {
            while (stream.ReadNextPropertyID(out uint propertyID)) {
                switch (propertyID) {
                    case (uint)PropertyID.SceneId: {
                        int previousValue = _sceneId;
                        _sceneId = (int)stream.ReadVarint32();
                        bool sceneIdExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.sceneIdSet);
                        if (!sceneIdExistsInChangeCache && _sceneId != previousValue) {
                            FireSceneIdDidChange(_sceneId);
                        }
                        break;
                    }
                    case (uint)PropertyID.SecondsDelay: {
                        int previousValue = _secondsDelay;
                        _secondsDelay = (int)stream.ReadVarint32();
                        bool secondsDelayExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.secondsDelaySet);
                        if (!secondsDelayExistsInChangeCache && _secondsDelay != previousValue) {
                            FireSecondsDelayDidChange(_secondsDelay);
                        }
                        break;
                    }
                    default: {
                        stream.SkipProperty();
                        break;
                    }
                }
            }
        }
        
        #region Cache Operations
        
        private StreamEventDispatcher _streamEventDispatcher;
        
        private void FlattenCache() {
            _sceneId = sceneId;
            _secondsDelay = secondsDelay;
            _cache.Clear();
        }
        
        private void ClearCache(uint updateID) {
            _cache.RemoveUpdateFromInflight(updateID);
        }
        
        private void ClearCacheOnStreamCallback(StreamContext context) {
            if (_streamEventDispatcher != context.dispatcher) {
                UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
            }
            _streamEventDispatcher = context.dispatcher;
            _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
        }
        
        private void UnsubscribeClearCacheCallback() {
            if (_streamEventDispatcher != null) {
                _streamEventDispatcher.RemoveStreamCallback(ClearCache);
                _streamEventDispatcher = null;
            }
        }
        
        #endregion
    }
}
/* ----- End Normal Autogenerated Code ----- */
