using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;
using Normal.Realtime;

namespace Assets.Scripts
{
    [RealtimeModel]
    public partial class VideoSelectSyncModel
    {
        // 4, 14
        [RealtimeProperty(1, true, true)] private int _videoId;
    }
}

/* ----- Begin Normal Autogenerated Code ----- */
namespace Assets.Scripts {
    public partial class VideoSelectSyncModel : RealtimeModel {
        public int videoId {
            get {
                return _cache.LookForValueInCache(_videoId, entry => entry.videoIdSet, entry => entry.videoId);
            }
            set {
                if (this.videoId == value) return;
                _cache.UpdateLocalCache(entry => { entry.videoIdSet = true; entry.videoId = value; return entry; });
                InvalidateReliableLength();
                FireVideoIdDidChange(value);
            }
        }
        
        public delegate void PropertyChangedHandler<in T>(VideoSelectSyncModel model, T value);
        public event PropertyChangedHandler<int> videoIdDidChange;
        
        private struct LocalCacheEntry {
            public bool videoIdSet;
            public int videoId;
        }
        
        private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
        
        public enum PropertyID : uint {
            VideoId = 14,
        }
        
        public VideoSelectSyncModel() : this(null) {
        }
        
        public VideoSelectSyncModel(RealtimeModel parent) : base(null, parent) {
        }
        
        protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
            UnsubscribeClearCacheCallback();
        }
        
        private void FireVideoIdDidChange(int value) {
            try {
                videoIdDidChange?.Invoke(this, value);
            } catch (System.Exception exception) {
                UnityEngine.Debug.LogException(exception);
            }
        }
        
        protected override int WriteLength(StreamContext context) {
            int length = 0;
            if (context.fullModel) {
                FlattenCache();
                length += WriteStream.WriteVarint32Length((uint)PropertyID.VideoId, (uint)_videoId);
            } else if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.videoIdSet) {
                    length += WriteStream.WriteVarint32Length((uint)PropertyID.VideoId, (uint)entry.videoId);
                }
            }
            return length;
        }
        
        protected override void Write(WriteStream stream, StreamContext context) {
            var didWriteProperties = false;
            
            if (context.fullModel) {
                stream.WriteVarint32((uint)PropertyID.VideoId, (uint)_videoId);
            } else if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.videoIdSet) {
                    _cache.PushLocalCacheToInflight(context.updateID);
                    ClearCacheOnStreamCallback(context);
                }
                if (entry.videoIdSet) {
                    stream.WriteVarint32((uint)PropertyID.VideoId, (uint)entry.videoId);
                    didWriteProperties = true;
                }
                
                if (didWriteProperties) InvalidateReliableLength();
            }
        }
        
        protected override void Read(ReadStream stream, StreamContext context) {
            while (stream.ReadNextPropertyID(out uint propertyID)) {
                switch (propertyID) {
                    case (uint)PropertyID.VideoId: {
                        int previousValue = _videoId;
                        _videoId = (int)stream.ReadVarint32();
                        bool videoIdExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.videoIdSet);
                        if (!videoIdExistsInChangeCache && _videoId != previousValue) {
                            FireVideoIdDidChange(_videoId);
                        }
                        break;
                    }
                    default: {
                        stream.SkipProperty();
                        break;
                    }
                }
            }
        }
        
        #region Cache Operations
        
        private StreamEventDispatcher _streamEventDispatcher;
        
        private void FlattenCache() {
            _videoId = videoId;
            _cache.Clear();
        }
        
        private void ClearCache(uint updateID) {
            _cache.RemoveUpdateFromInflight(updateID);
        }
        
        private void ClearCacheOnStreamCallback(StreamContext context) {
            if (_streamEventDispatcher != context.dispatcher) {
                UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
            }
            _streamEventDispatcher = context.dispatcher;
            _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
        }
        
        private void UnsubscribeClearCacheCallback() {
            if (_streamEventDispatcher != null) {
                _streamEventDispatcher.RemoveStreamCallback(ClearCache);
                _streamEventDispatcher = null;
            }
        }
        
        #endregion
    }
}
/* ----- End Normal Autogenerated Code ----- */
