using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;

namespace Assets.Scripts
{
    [RealtimeModel]
    public partial class ScreenSelectSyncModel
    {
        [RealtimeProperty(3, true, true)] private int _screenId;
    }

/* ----- Begin Normal Autogenerated Code ----- */
    public partial class ScreenSelectSyncModel : IModel
    {
        // Properties
        public int screenId
        {
            get { return _cache.LookForValueInCache(_screenId, entry => entry.screenIdSet, entry => entry.screenId); }
            set
            {
                if (value == screenId) return;
                _cache.UpdateLocalCache(entry =>
                {
                    entry.screenIdSet = true;
                    entry.screenId = value;
                    return entry;
                });
                FireScreenIdDidChange(value);
            }
        }

        // Events
        public delegate void ScreenIdDidChange(ScreenSelectSyncModel model, int value);

        public event ScreenIdDidChange screenIdDidChange;

        // Delta updates
        private struct LocalCacheEntry
        {
            public bool screenIdSet;
            public int screenId;
        }

        private LocalChangeCache<LocalCacheEntry> _cache;

        public ScreenSelectSyncModel()
        {
            _cache = new LocalChangeCache<LocalCacheEntry>();
        }

        // Events
        public void FireScreenIdDidChange(int value)
        {
            try
            {
                if (screenIdDidChange != null)
                    screenIdDidChange(this, value);
            }
            catch (System.Exception exception)
            {
                Debug.LogException(exception);
            }
        }

        // Serialization
        enum PropertyID
        {
            ScreenId = 1,
        }

        public int WriteLength(StreamContext context)
        {
            int length = 0;

            if (context.fullModel)
            {
                // Mark unreliable properties as clean and flatten the in-flight cache.
                // TODO: Move this out of WriteLength() once we have a prepareToWrite method.
                _screenId = screenId;
                _cache.Clear();

                // Write all properties
                length += WriteStream.WriteVarint32Length((uint) PropertyID.ScreenId, (uint) _screenId);
            }
            else
            {
                // Reliable properties
                if (context.reliableChannel)
                {
                    LocalCacheEntry entry = _cache.localCache;
                    if (entry.screenIdSet)
                        length += WriteStream.WriteVarint32Length((uint) PropertyID.ScreenId, (uint) entry.screenId);
                }
            }

            return length;
        }

        public void Write(WriteStream stream, StreamContext context)
        {
            if (context.fullModel)
            {
                // Write all properties
                stream.WriteVarint32((uint) PropertyID.ScreenId, (uint) _screenId);
            }
            else
            {
                // Reliable properties
                if (context.reliableChannel)
                {
                    LocalCacheEntry entry = _cache.localCache;
                    if (entry.screenIdSet)
                        _cache.PushLocalCacheToInflight(context.updateID);

                    if (entry.screenIdSet)
                        stream.WriteVarint32((uint) PropertyID.ScreenId, (uint) entry.screenId);
                }
            }
        }

        public void Read(ReadStream stream, StreamContext context)
        {
            bool screenIdExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.screenIdSet);

            // Remove from in-flight
            if (context.deltaUpdatesOnly && context.reliableChannel)
                _cache.RemoveUpdateFromInflight(context.updateID);

            // Loop through each property and deserialize
            uint propertyID;
            while (stream.ReadNextPropertyID(out propertyID))
            {
                switch (propertyID)
                {
                    case (uint) PropertyID.ScreenId:
                    {
                        int previousValue = _screenId;

                        _screenId = (int) stream.ReadVarint32();

                        if (!screenIdExistsInChangeCache && _screenId != previousValue)
                            FireScreenIdDidChange(_screenId);
                        break;
                    }
                    default:
                        stream.SkipProperty();
                        break;
                }
            }
        }
    }

/* ----- End Normal Autogenerated Code ----- */
}