using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;

namespace Assets.Scripts
{
    [RealtimeModel]
    public partial class StreamSelectSyncModel
    {
        // 6
        [RealtimeProperty(10, true, true)] private int _streamId;
    }

/* ----- Begin Normal Autogenerated Code ----- */
    public partial class StreamSelectSyncModel : IModel
    {
        // Properties
        public int streamId
        {
            get { return _cache.LookForValueInCache(_streamId, entry => entry.streamIdSet, entry => entry.streamId); }
            set
            {
                if (value == streamId) return;
                _cache.UpdateLocalCache(entry =>
                {
                    entry.streamIdSet = true;
                    entry.streamId = value;
                    return entry;
                });
                FireStreamIdDidChange(value);
            }
        }

        // Events
        public delegate void StreamIdDidChange(StreamSelectSyncModel model, int value);

        public event StreamIdDidChange streamIdDidChange;

        // Delta updates
        private struct LocalCacheEntry
        {
            public bool streamIdSet;
            public int streamId;
        }

        private LocalChangeCache<LocalCacheEntry> _cache;

        public StreamSelectSyncModel()
        {
            _cache = new LocalChangeCache<LocalCacheEntry>();
        }

        // Events
        public void FireStreamIdDidChange(int value)
        {
            try
            {
                if (streamIdDidChange != null)
                    streamIdDidChange(this, value);
            }
            catch (System.Exception exception)
            {
                Debug.LogException(exception);
            }
        }

        // Serialization
        enum PropertyID
        {
            StreamId = 1,
        }

        public int WriteLength(StreamContext context)
        {
            int length = 0;

            if (context.fullModel)
            {
                // Mark unreliable properties as clean and flatten the in-flight cache.
                // TODO: Move this out of WriteLength() once we have a prepareToWrite method.
                _streamId = streamId;
                _cache.Clear();

                // Write all properties
                length += WriteStream.WriteVarint32Length((uint) PropertyID.StreamId, (uint) _streamId);
            }
            else
            {
                // Reliable properties
                if (context.reliableChannel)
                {
                    LocalCacheEntry entry = _cache.localCache;
                    if (entry.streamIdSet)
                        length += WriteStream.WriteVarint32Length((uint) PropertyID.StreamId, (uint) entry.streamId);
                }
            }

            return length;
        }

        public void Write(WriteStream stream, StreamContext context)
        {
            if (context.fullModel)
            {
                // Write all properties
                stream.WriteVarint32((uint) PropertyID.StreamId, (uint) _streamId);
            }
            else
            {
                // Reliable properties
                if (context.reliableChannel)
                {
                    LocalCacheEntry entry = _cache.localCache;
                    if (entry.streamIdSet)
                        _cache.PushLocalCacheToInflight(context.updateID);

                    if (entry.streamIdSet)
                        stream.WriteVarint32((uint) PropertyID.StreamId, (uint) entry.streamId);
                }
            }
        }

        public void Read(ReadStream stream, StreamContext context)
        {
            bool streamIdExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.streamIdSet);

            // Remove from in-flight
            if (context.deltaUpdatesOnly && context.reliableChannel)
                _cache.RemoveUpdateFromInflight(context.updateID);

            // Loop through each property and deserialize
            uint propertyID;
            while (stream.ReadNextPropertyID(out propertyID))
            {
                switch (propertyID)
                {
                    case (int) PropertyID.StreamId:
                    {
                        int previousValue = _streamId;

                        _streamId = (int) stream.ReadVarint32();

                        if (!streamIdExistsInChangeCache && _streamId != previousValue)
                            FireStreamIdDidChange(_streamId);
                        break;
                    }
                    default:
                        stream.SkipProperty();
                        break;
                }
            }
        }
    }

/* ----- End Normal Autogenerated Code ----- */
}