using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class VideoSelectSyncModel
{
    [RealtimeProperty(4, true, true)]
    private int _videoId;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class VideoSelectSyncModel : IModel {
    // Properties
    public int videoId {
        get { return _cache.LookForValueInCache(_videoId, entry => entry.videoIdSet, entry => entry.videoId); }
        set { if (value == videoId) return; _cache.UpdateLocalCache(entry => { entry.videoIdSet = true; entry.videoId = value; return entry; }); FireVideoIdDidChange(value); }
    }
    
    // Events
    public delegate void VideoIdDidChange(VideoSelectSyncModel model, int value);
    public event         VideoIdDidChange videoIdDidChange;
    
    // Delta updates
    private struct LocalCacheEntry {
        public bool videoIdSet;
        public int  videoId;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache;
    
    public VideoSelectSyncModel() {
        _cache = new LocalChangeCache<LocalCacheEntry>();
    }
    
    // Events
    public void FireVideoIdDidChange(int value) {
        try {
            if (videoIdDidChange != null)
                videoIdDidChange(this, value);
        } catch (System.Exception exception) {
            Debug.LogException(exception);
        }
    }
    
    // Serialization
    enum PropertyID {
        VideoId = 1,
    }
    
    public int WriteLength(StreamContext context) {
        int length = 0;
        
        if (context.fullModel) {
            // Mark unreliable properties as clean and flatten the in-flight cache.
            // TODO: Move this out of WriteLength() once we have a prepareToWrite method.
            _videoId = videoId;
            _cache.Clear();
            
            // Write all properties
            length += WriteStream.WriteVarint32Length((uint)PropertyID.VideoId, (uint)_videoId);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.videoIdSet)
                    length += WriteStream.WriteVarint32Length((uint)PropertyID.VideoId, (uint)entry.videoId);
            }
        }
        
        return length;
    }
    
    public void Write(WriteStream stream, StreamContext context) {
        if (context.fullModel) {
            // Write all properties
            stream.WriteVarint32((uint)PropertyID.VideoId, (uint)_videoId);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.videoIdSet)
                    _cache.PushLocalCacheToInflight(context.updateID);
                
                if (entry.videoIdSet)
                    stream.WriteVarint32((uint)PropertyID.VideoId, (uint)entry.videoId);
            }
        }
    }
    
    public void Read(ReadStream stream, StreamContext context) {
        bool videoIdExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.videoIdSet);
        
        // Remove from in-flight
        if (context.deltaUpdatesOnly && context.reliableChannel)
            _cache.RemoveUpdateFromInflight(context.updateID);
        
        // Loop through each property and deserialize
        uint propertyID;
        while (stream.ReadNextPropertyID(out propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.VideoId: {
                    int previousValue = _videoId;
                    
                    _videoId = (int)stream.ReadVarint32();
                    
                    if (!videoIdExistsInChangeCache && _videoId != previousValue)
                        FireVideoIdDidChange(_videoId);
                    break;
                }
                default:
                    stream.SkipProperty();
                    break;
            }
        }
    }
}
/* ----- End Normal Autogenerated Code ----- */
