using Normal.Realtime.Serialization;
using Normal.Realtime;

namespace Assets.Scripts
{
    [RealtimeModel]
    public partial class FormationSelectSyncModel
    {   
        [RealtimeProperty(3, true, true)] private int _formationId;
    }
}

/* ----- Begin Normal Autogenerated Code ----- */
namespace Assets.Scripts {
    public partial class FormationSelectSyncModel : RealtimeModel {
        public int formationId {
            get {
                return _formationIdProperty.value;
            }
            set {
                if (_formationIdProperty.value == value) return;
                _formationIdProperty.value = value;
                InvalidateReliableLength();
                FireFormationIdDidChange(value);
            }
        }
        
        public delegate void PropertyChangedHandler<in T>(FormationSelectSyncModel model, T value);
        public event PropertyChangedHandler<int> formationIdDidChange;
        
        public enum PropertyID : uint {
            FormationId = 3,
        }
        
        #region Properties
        
        private ReliableProperty<int> _formationIdProperty;
        
        #endregion
        
        public FormationSelectSyncModel() : base(null) {
            _formationIdProperty = new ReliableProperty<int>(3, _formationId);
        }
        
        protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
            _formationIdProperty.UnsubscribeCallback();
        }
        
        private void FireFormationIdDidChange(int value) {
            try {
                formationIdDidChange?.Invoke(this, value);
            } catch (System.Exception exception) {
                UnityEngine.Debug.LogException(exception);
            }
        }
        
        protected override int WriteLength(StreamContext context) {
            var length = 0;
            length += _formationIdProperty.WriteLength(context);
            return length;
        }
        
        protected override void Write(WriteStream stream, StreamContext context) {
            var writes = false;
            writes |= _formationIdProperty.Write(stream, context);
            if (writes) InvalidateContextLength(context);
        }
        
        protected override void Read(ReadStream stream, StreamContext context) {
            var anyPropertiesChanged = false;
            while (stream.ReadNextPropertyID(out uint propertyID)) {
                var changed = false;
                switch (propertyID) {
                    case (uint) PropertyID.FormationId: {
                        changed = _formationIdProperty.Read(stream, context);
                        if (changed) FireFormationIdDidChange(formationId);
                        break;
                    }
                    default: {
                        stream.SkipProperty();
                        break;
                    }
                }
                anyPropertiesChanged |= changed;
            }
            if (anyPropertiesChanged) {
                UpdateBackingFields();
            }
        }
        
        private void UpdateBackingFields() {
            _formationId = formationId;
        }
        
    }
}
/* ----- End Normal Autogenerated Code ----- */
